services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: vs_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      retries: 3
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
