name: Lint & Test
on:
  pull_request:
    branches: "*"
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  push:
    branches:
      - main
      - staging
    paths:
      - '**.go'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Services
        run: go build -v ./...
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Golang ci Action
        uses: golangci/golangci-lint-action@v4
        with:
          args: --timeout=3m
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run Unit tests
        run: go test ./... -short
